#!/bin/bash -eu
set -o pipefail

# All fetched files should be put in the feed directory.
pushd "${PIPELINE_FEED_DIR}" &> /dev/null

# Clear past fetched data if step is run multiple times.
rm -rf "${PIPELINE_FEED_DIR}"/*

# For data persistence with cloud storage, this should be moved to the
# generate step and this file would fetch the data from the cloud.
# Fetch the data, convert the file encoding to UTF-8, and save to file.
curl 'https://data.humdata.org/dataset/7c8e3b81-1a34-482a-8ebe-14dde43f1b5b/resource/09b9ffeb-e6f6-4605-b9d1-e46c81a33990/download/fts_incoming_funding_moz.csv' \
    > world-bank-urban-development-indicators-for-mozambique.csv

popd &> /dev/null
