#!/bin/bash -eu
set -o pipefail

# The data validation pipeline is used for verifying the 'generate', 'process',
# and 'index' pipelines. The datastores populated by the 'index' step should
# match the values created by the 'process' pipeline. If available, an
# independent source of truth should be used to validate the values provided by
# the 'generate' and 'process' pipelines.

export ZEN_ENV='SITECODE'

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd -P)
ZEN_SRC_ROOT=$(git rev-parse --show-toplevel)

ZEUS_ID='SAMPLE/validate'
ZEUS_OUT_DIRS='feed,out,tmp'
ZEUS_ROOT_DIR="${SCRIPT_DIR}/run"
ZEUS_BIN_DIR="${SCRIPT_DIR}/../bin"
ZEUS_UTILS_DIR="${ZEN_SRC_ROOT}/util/pipeline"
ZEUS_PUBLISH_DIR="/home/share/data/SAMPLE/validate"

ZEUS_CMD="\
zeus \
  --id=${ZEUS_ID} \
  --root=${ZEUS_ROOT_DIR} \
  --bin_root=${ZEUS_BIN_DIR} \
  --utils_root=${ZEUS_UTILS_DIR} \
  --out_dirs=${ZEUS_OUT_DIRS} \
  --publish_root=${ZEUS_PUBLISH_DIR} \
"

${ZEUS_CMD} $@
