"""Change user_query_session users to cascade user deletes

Revision ID: 05cc6c8d7b0a
Revises: f66b2477cc4d
Create Date: 2020-04-24 17:06:14.214254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cc6c8d7b0a'
down_revision = 'f66b2477cc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_session', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_constraint('valid_user', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_user', 'user', ['user_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_session', schema=None) as batch_op:
        batch_op.drop_constraint('valid_user', type_='foreignkey')
        batch_op.create_foreign_key('valid_user', 'user', ['user_id'], ['id'])
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
