"""Add 'is_important' column to dashboards. Mark all dashboards as unimportant by default.

Revision ID: 0c2dd30d5bee
Revises: 9a211d5417c7
Create Date: 2019-02-26 14:12:23.351732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2dd30d5bee'
down_revision = '9a211d5417c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('is_important')

    # ### end Alembic commands ###
