'''Remove name column from Dashboard

Revision ID: 12786dfb3980
Revises: 18429a152520
Create Date: 2018-04-13 14:22:09.739291

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12786dfb3980'
down_revision = '18429a152520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
