# pylint: disable=invalid-name
"""Use timezone for started_at and disallow nulls for successul

Revision ID: 1e6aa4f75d79
Revises: b281ae64d45d
Create Date: 2022-12-13 12:50:35.049549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e6aa4f75d79'
down_revision = 'b281ae64d45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_run', schema=None) as batch_op:
        batch_op.alter_column(
            'started_at',
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('now()'),
        )
        batch_op.alter_column('successful', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_run', schema=None) as batch_op:
        batch_op.alter_column('successful', existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            'started_at',
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('now()'),
        )
    # ### end Alembic commands ###
