"""Create table for DashboardSession

Revision ID: 1fe113553bb6
Revises: bb520d4aa8fd
Create Date: 2020-11-20 12:23:00.111373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fe113553bb6'
down_revision = 'bb520d4aa8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dashboard_session',
        sa.Column('uuid', sa.String(), nullable=False),
        sa.Column('dashboard_id', sa.Integer(), nullable=False),
        sa.Column('data_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ['dashboard_id'],
            ['dashboard.id'],
            name='valid_dashboard',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uuid'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_session')
    # ### end Alembic commands ###
