"""Add Case Management Models

Revision ID: 23525d8da689
Revises: 70e1269c0db2
Create Date: 2019-04-19 13:52:27.108759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23525d8da689'
down_revision = '70e1269c0db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('case_spec', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('case_event',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('date', sa.String(), nullable=True),
                    sa.Column('type', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_event')
    op.drop_table('case')
    # ### end Alembic commands ###
