"""Add back id column to security_group_users model.

Revision ID: 25faffac83d1
Revises: a43bff717c71
Create Date: 2020-05-13 16:52:54.435115

"""
from alembic import op
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25faffac83d1'
down_revision = 'a43bff717c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('security_group_users_id_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_group_users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'id',
                sa.Integer(),
                nullable=False,
                server_default=sa.text(
                    "nextval('security_group_users_id_seq'::regclass)"
                ),
            )
        )
        batch_op.drop_constraint('unique_group_and_user')
        batch_op.create_primary_key('security_group_users_pkey', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_group_users', schema=None) as batch_op:
        batch_op.drop_constraint('security_group_users_pkey')
        batch_op.create_primary_key('unique_group_and_user', ['group_id', 'user_id'])
        batch_op.drop_column('id')
    op.execute(DropSequence(Sequence('security_group_users_id_seq')))

    # ### end Alembic commands ###
