'''Add overwrite fields for configuration table.

Revision ID: 2c2d9357157c
Revises: 58add9b07431
Create Date: 2018-09-13 11:56:10.294447

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c2d9357157c'
down_revision = '58add9b07431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('value', new_column_name='overwritten_value', nullable=True)
        batch_op.add_column(sa.Column('overwritten', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('overwritten_value', new_column_name='value', nullable=False)
        batch_op.drop_column('overwritten')

    # ### end Alembic commands ###
