"""empty message

Revision ID: 34ef9489bfc1
Revises: 915286bb532c
Create Date: 2020-05-26 14:59:22.898861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ef9489bfc1'
down_revision = '915286bb532c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_metadata_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'valid_case_type', 'case_type', ['case_type_id'], ['id'], ondelete='CASCADE'
        )
    op.execute(
        'update case_metadata_type set case_type_id = T.case_type_id from case_type_default_metadata T where id = T.case_metadata_type_id;'
    )
    op.alter_column('case_metadata_type', 'case_type_id', nullable=False)
    op.drop_table('case_type_default_metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_metadata_type', schema=None) as batch_op:
        batch_op.drop_constraint('valid_case_type', type_='foreignkey')
        batch_op.drop_column('case_type_id')

    op.create_table(
        'case_type_default_metadata',
        sa.Column('case_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'case_metadata_type_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['case_metadata_type_id'],
            ['case_metadata_type.id'],
            name='valid_case_metadata_type',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['case_type_id'],
            ['case_type.id'],
            name='valid_case_type',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'case_type_id',
            'case_metadata_type_id',
            name='case_type_default_metadata_pkey',
        ),
    )
    # ### end Alembic commands ###
