"""Add dashboard views metadata

Revision ID: 3badb035b6ba
Revises: 4ba4caf5d5b4
Create Date: 2019-05-28 11:00:59.687428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3badb035b6ba'
down_revision = '4ba4caf5d5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('total_views', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('dashboard_user_metadata', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('views_by_user', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('total_views')

    with op.batch_alter_table('dashboard_user_metadata', schema=None) as batch_op:
        batch_op.drop_column('views_by_user')
    # ### end Alembic commands ###
