"""Add modified/creation statistics to the Dashboard Table

Revision ID: 3c9bde88ba8a
Revises: 0331609ed38d
Create Date: 2019-01-10 12:23:29.563074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9bde88ba8a'
down_revision = '0331609ed38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
