'''Convert Alert Defintions to JSONB

Revision ID: 4189ebe6c090
Revises: 961f42e2e5e9
Create Date: 2018-06-08 17:11:58.382894

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql.json import JSONB
from sqlalchemy.ext.mutable import MutableList


# revision identifiers, used by Alembic.
revision = '4189ebe6c090'
down_revision = '961f42e2e5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_definitions', 'checks', type_=MutableList.as_mutable(JSONB()), postgresql_using=('checks::json'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_definitions', 'checks', type_=sa.JSON(), postgresql_using=('checks::json'))

    # ### end Alembic commands ###
