"""Allow user deletions for history records without deleting the underlying history record.

Revision ID: 43f128934e5d
Revises: 3badb035b6ba
Create Date: 2019-05-29 12:00:59.358253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f128934e5d'
down_revision = '3badb035b6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.drop_constraint(u'valid_user', type_='foreignkey')
        batch_op.create_foreign_key('valid_user', 'user', ['user_id'], [
                                    'id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.drop_constraint('valid_user', type_='foreignkey')
        batch_op.create_foreign_key(u'valid_user', 'user', ['user_id'], [
                                    'id'], ondelete=u'RESTRICT')
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
    # ### end Alembic commands ###
