# pylint: disable=C0103
"""Add Data Digest Overview

Revision ID: 4d1872f4a1d3
Revises: c6c1151430dd
Create Date: 2021-03-01 14:50:29.900452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1872f4a1d3'
down_revision = 'c6c1151430dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'data_digest_overview',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('generation_datetime', sa.DateTime(), nullable=True),
        sa.Column(
            'digest_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_digest_overview')
    # ### end Alembic commands ###
