"""Add use recipient permissions and use single email thread columns

Revision ID: 65fda57202a5
Revises: 1fe113553bb6
Create Date: 2021-01-12 21:16:36.685907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fda57202a5'
down_revision = '1fe113553bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_schedule', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'use_recipient_query_policy',
                sa.Boolean(),
                server_default='TRUE',
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'use_single_email_thread',
                sa.Boolean(),
                server_default='FALSE',
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_schedule', schema=None) as batch_op:
        batch_op.drop_column('use_single_email_thread')
        batch_op.drop_column('use_recipient_query_policy')

    # ### end Alembic commands ###
