'''Enforce non-nullable resource_type_id column for Roles

Revision ID: 6ba94d12d7d8
Revises: c04c7f84420e
Create Date: 2017-09-13 22:32:17.647322

'''
from alembic import op
import sqlalchemy as sa

from web.server.migrations.seed_scripts.seed_6ba94d12d7d8 import prepopulate_data

# revision identifiers, used by Alembic.
revision = '6ba94d12d7d8'
down_revision = 'c04c7f84420e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('resource_type_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
    # ### end Alembic commands ###
    prepopulate_data(op)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('resource_type_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###
