"""Add self serve summary table

Revision ID: 6d4dc6809e6c
Revises: c8a9fb8f786b
Create Date: 2021-03-31 11:21:12.392598

"""
from alembic import op
import sqlalchemy as sa

# pylint: disable=invalid-name
# revision identifiers, used by Alembic.
revision = '6d4dc6809e6c'
down_revision = 'c8a9fb8f786b'
branch_labels = None
depends_on = None


def upgrade():
    # pylint: disable=no-member
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'self_serve_source',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(length=100), nullable=True),
        sa.Column('source_name', sa.String(length=100), nullable=True),
        sa.Column('file_summary_id', sa.Integer(), nullable=True),
        sa.Column(
            'last_modified',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['file_summary_id'], ['data_upload_file_summary.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # pylint: disable=no-member
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_serve_source')
    # ### end Alembic commands ###
