# pylint: disable=invalid-name
"""This migration adds a created, last_modified datetime fields to the
data catalog tables.

Revision ID: 70835f75f7c6
Revises: 97b0abb262bf
Create Date: 2022-12-15 11:03:54.777896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70835f75f7c6'
down_revision = '97b0abb262bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('dataprep_flow', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('dimension_category', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('dimension_category_mapping', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('field_category_mapping', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('field_dimension_mapping', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table(
        'field_pipeline_datasource_mapping', schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('pipeline_datasource', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_modified',
                sa.DateTime(),
                server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created',
                sa.DateTime(),
                server_default=sa.text('now()'),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.drop_column('created')

    with op.batch_alter_table('pipeline_datasource', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table(
        'field_pipeline_datasource_mapping', schema=None
    ) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('field_dimension_mapping', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('field_category_mapping', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('dimension_category_mapping', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('dimension_category', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('dataprep_flow', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
