"""Add history table and indicator constituents for calculated indicators

Revision ID: 70e1269c0db2
Revises: f2b1e3aa0001
Create Date: 2019-04-03 12:07:35.798936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70e1269c0db2'
down_revision = 'f2b1e3aa0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_records_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_records_object_type'), ['object_type'], unique=False)

    op.create_table('indicator_constituents',
    sa.Column('calculated_indicator_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculated_indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('calculated_indicator_id', 'indicator_id')
    )
    with op.batch_alter_table(u'indicator_groups', schema=None) as batch_op:
        batch_op.alter_column('text_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('unique_group_text_id', ['text_id'])

    with op.batch_alter_table(u'indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.String(), nullable=True))
        batch_op.create_unique_constraint('unique_indicator_text_id', ['text_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'indicators', schema=None) as batch_op:
        batch_op.drop_constraint('unique_indicator_text_id', type_='unique')
        batch_op.drop_column('formula')

    with op.batch_alter_table(u'indicator_groups', schema=None) as batch_op:
        batch_op.drop_constraint('unique_group_text_id', type_='unique')
        batch_op.alter_column('text_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('indicator_constituents')
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_records_object_type'))
        batch_op.drop_index(batch_op.f('ix_history_records_object_id'))

    op.drop_table('history_records')
    # ### end Alembic commands ###
