'''Create schema for Grid Dashboards in SQL.

Revision ID: 8d2c718eadfa
Revises: b619b8b27577
Create Date: 2018-04-09 23:58:37.447150

'''

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2c718eadfa'
down_revision = 'b619b8b27577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='valid_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='valid_dashboard_resource', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('resource_id'),
    sa.UniqueConstraint('slug')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard')
    # ### end Alembic commands ###
