'''Add support for public roles in the database

Revision ID: 8e52d9ff28d7
Revises: ccecea0dd59d
Create Date: 2017-12-12 11:14:11.776131

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e52d9ff28d7'
down_revision = 'deed35b6fd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='valid_resource', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='valid_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_roles')
    # ### end Alembic commands ###
