# pylint: disable=invalid-name
"""
Pipeline entity type metadata columns migration which also generates data for the new table
with the migration seed script.

Revision ID: 97b0abb262bf
Revises: ed9866de10d8
Create Date: 2022-12-20 19:23:23.185484

"""
from alembic import op
import sqlalchemy as sa
from web.server.migrations.seed_scripts.seed_97b0abb262bf_entity_type_metadata_columns import (
    upvert_data,
    downvert_data,
)


# revision identifiers, used by Alembic.
revision = '97b0abb262bf'
down_revision = 'ed9866de10d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'metadata_column',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('filterable', sa.Boolean(), nullable=False),
        sa.Column('sortable', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'metadata_pipeline_entity_type_mappings',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('metadata_column_id', sa.Integer(), nullable=False),
        sa.Column('pipeline_entity_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['metadata_column_id'],
            ['metadata_column.id'],
            name='valid_metadata_column',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['pipeline_entity_type_id'],
            ['pipeline_entity_type.id'],
            name='valid_pipeline_entity_type',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    upvert_data(op)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    downvert_data(op)

    op.drop_table('metadata_pipeline_entity_type_mappings')
    op.drop_table('metadata_column')

    # ### end Alembic commands ###
