# pylint: disable=invalid-name
"""Adds fields to dashboard to control download permissions for registered and unregistered users

Revision ID: 99859a8ef2fc
Revises: 189373be1240
Create Date: 2023-04-21 13:44:48.207329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99859a8ef2fc'
down_revision = '189373be1240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'registered_users_can_download_data',
                sa.Boolean(),
                server_default='false',
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'unregistered_users_can_download_data',
                sa.Boolean(),
                server_default='false',
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('unregistered_users_can_download_data')
        batch_op.drop_column('registered_users_can_download_data')

    # ### end Alembic commands ###
