"""Basic Indicator tables

Revision ID: a06ef37f9e93
Revises: 0c2dd30d5bee
Create Date: 2019-02-04 13:07:18.270479

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a06ef37f9e93'
down_revision = '0c2dd30d5bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.String(), nullable=False),
    sa.Column('group_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['indicator_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    # Roll back of seed data not required because dropping tables resets
    # the database to the exact before upgrade state.
    op.drop_table('indicators')
    op.drop_table('indicator_groups')
    # ### end Alembic commands ###
