"""empty message

Revision ID: aad4ae0ffda6
Revises: 522563aa77c7
Create Date: 2021-02-08 16:05:41.879077

"""
# pylint: skip-file
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad4ae0ffda6'
down_revision = '522563aa77c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dimension_category',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('parent_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['dimension_category.id'],
            name='parent_category',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    # Add the `root` dimension_category that should always be present.
    op.execute(
        '''INSERT INTO dimension_category (id, name) VALUES ('root', '__root__')
        ON CONFLICT (id) DO UPDATE SET name = '__root__'
        '''
    )

    op.drop_table('category_to_category_mapping')

    # NOTE(stephen): Safely clearing out the dimension_category_mapping table since it
    # has some issues upgrading from using the `category` table to the
    # `dimension_category` table. This is safe because there are no data catalog users
    # right now and it is easier than figuring out which categories to migrate.
    op.execute('TRUNCATE TABLE dimension_category_mapping RESTART IDENTITY')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            'parent_category', 'category', ['parent_id'], ['id'], ondelete='CASCADE'
        )

        # Add the `root` category that should always be present.
        batch_op.execute(
            '''INSERT INTO category (id, name) VALUES ('root', '__root__')
            ON CONFLICT (id) DO UPDATE SET name = '__root__'
            '''
        )

    with op.batch_alter_table('dimension_category_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('valid_category', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_category',
            'dimension_category',
            ['category_id'],
            ['id'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE(stephen): Safely clearing out the dimension_category_mapping table since it
    # has some issues downgrading back to using the `category` table for its mappings.
    # This is safe because there are no data catalog users right now.
    op.execute('TRUNCATE TABLE dimension_category_mapping RESTART IDENTITY')
    with op.batch_alter_table('dimension_category_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('valid_category', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_category', 'category', ['category_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('parent_category', type_='foreignkey')
        batch_op.drop_column('parent_id')

    op.drop_table('dimension_category')

    op.create_table(
        'category_to_category_mapping',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'parent_category_id', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['category_id'], ['category.id'], name='valid_category', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['parent_category_id'],
            ['category.id'],
            name='valid_parent_category',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name='category_to_category_mapping_pkey'),
        sa.UniqueConstraint(
            'category_id',
            'parent_category_id',
            name='category_to_category_mapping_category_id_parent_category_id_key',
        ),
    )
    # ### end Alembic commands ###
