"""Add dashboard_report_groups

Revision ID: aae58915bafb
Revises: 6d4dc6809e6c
Create Date: 2021-04-19 17:33:03.886466

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aae58915bafb'
down_revision = '6d4dc6809e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dashboard_report_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('dashboard_report_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['dashboard_report_id'],
            ['dashboard_report_schedule.id'],
            name='valid_dashboard_report_group',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['security_group.id'],
            name='valid_security_group_dashboard_report',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_report_groups')
    # ### end Alembic commands ###
