'''Prevent Role and Permission deletes until a Resource Type is completely deleted. Move
Configuration and Dashboard Models to use JSONB

Revision ID: ad0d35c05a7d
Revises: 4189ebe6c090
Create Date: 2018-06-14 08:48:35.069437

'''
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.mutable import MutableDict

# revision identifiers, used by Alembic.
revision = 'ad0d35c05a7d'
down_revision = '4189ebe6c090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(u'valid_resource_type', type_='foreignkey')
        batch_op.create_foreign_key('valid_resource_type', 'resource_type', ['resource_type_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(u'valid_resource_type', type_='foreignkey')
        batch_op.create_foreign_key('valid_resource_type', 'resource_type', ['resource_type_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.alter_column(
        'dashboard',
        'specification',
        type_=MutableDict.as_mutable(JSONB()),
        nullable=False,
        postgresql_using=('specification::json'))

    op.alter_column(
        'configuration',
        'value',
        type_=JSONB(),
        nullable=False,
        postgresql_using=('value::json'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('valid_resource_type', type_='foreignkey')
        batch_op.create_foreign_key(u'valid_resource_type', 'resource_type', ['resource_type_id'], ['id'], ondelete=u'CASCADE')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint('valid_resource_type', type_='foreignkey')
        batch_op.create_foreign_key(u'valid_resource_type', 'resource_type', ['resource_type_id'], ['id'])

    op.alter_column(
        'dashboard',
        'specification',
        type_=sa.JSON(),
        nullable=False,
        postgresql_using=('specification::json'))

    op.alter_column(
        'configuration',
        'value',
        type_=sa.JSON(),
        nullable=False,
        postgresql_using=('value::json'))
    # ### end Alembic commands ###
