'''Prevent cascade deletion of resources, remove redundant id column in 'group_users' Table

Revision ID: b619b8b27577
Revises: be489b5a4343
Create Date: 2018-03-02 19:02:10.636780

'''

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b619b8b27577'
down_revision = 'be489b5a4343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_users', schema=None) as batch_op:
        batch_op.drop_column('id')
        batch_op.create_primary_key('unique_group_and_user', ['user_id', 'group_id'])

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_constraint(u'valid_resource_type', type_='foreignkey')
        batch_op.create_foreign_key('valid_resource_type', 'resource_type', ['resource_type_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_primary_key('unique_group_and_user', ['id', ])

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_constraint('valid_resource_type', type_='foreignkey')
        batch_op.create_foreign_key(u'valid_resource_type', 'resource_type', ['resource_type_id'], ['id'])

    # ### end Alembic commands ###
