# pylint: disable=invalid-name
"""Creates db tables for the new DV cache in the db instead of web server RAM

Revision ID: bcfc6763c18c
Revises: 99859a8ef2fc
Create Date: 2023-05-22 10:55:21.037367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcfc6763c18c'
down_revision = '3071258606d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dimension_value',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('datasources', postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column('dimension', sa.String(), nullable=False),
        sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('subtitle', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dimension', 'name', 'subtitle'),
    )
    with op.batch_alter_table('dimension_value', schema=None) as batch_op:
        batch_op.create_index(
            'datasources_idx', ['datasources'], unique=False, postgresql_using='gin'
        )

    op.create_table(
        'druid_datasource',
        sa.Column(
            'created',
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            'last_modified',
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('datasource', sa.String(), nullable=False),
        sa.Column('min_date', sa.Date(), nullable=False),
        sa.Column('max_date', sa.Date(), nullable=False),
        sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('datasource'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('druid_datasource')
    with op.batch_alter_table('dimension_value', schema=None) as batch_op:
        batch_op.drop_index('datasources_idx', postgresql_using='gin')

    op.drop_table('dimension_value')
    # ### end Alembic commands ###
