"""Create geo_dimension_metadata, hierarchical_dimension_metadata,
non_hierarchical_dimensions tables and updates existing dimension table.

Revision ID: de1372d2c1b3
Revises: 7d247dadfba0
Create Date: 2021-10-25 14:32:00.732369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1372d2c1b3'
down_revision = '7d247dadfba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'geo_dimension_metadata',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('lat_id', sa.String(), nullable=False),
        sa.Column('lon_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'], ['dimension.id'], name='valid_geo_dimension', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['lat_id'], ['dimension.id'], name='valid_lat_dimension', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['lon_id'], ['dimension.id'], name='valid_lon_dimension', ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'hierarchical_dimension_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dimension_id', sa.String(), nullable=False),
        sa.Column('unique_identifier_dimension_id', sa.String(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['dimension_id'],
            ['dimension.id'],
            name='valid_hierarchical_dimension',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['hierarchical_dimension_metadata.id'],
            name='valid_hierarchical_dimension_parent',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['unique_identifier_dimension_id'],
            ['dimension.id'],
            name='valid_unique_identifier_dimension_id',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'non_hierarchical_dimension',
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['dimension.id'],
            name='valid_non_hierarchical_dimension',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'authorizable', sa.Boolean(), server_default='false', nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                'filterable', sa.Boolean(), server_default='false', nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_column('filterable')
        batch_op.drop_column('authorizable')

    op.drop_table('non_hierarchical_dimension')
    op.drop_table('hierarchical_dimension_metadata')
    op.drop_table('geo_dimension_metadata')
    # ### end Alembic commands ###
