"""Add Mapped Locations table for storing user created location matches.

Revision ID: f2b1e3aa0001
Revises: a06ef37f9e93
Create Date: 2019-03-21 10:21:57.661938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b1e3aa0001'
down_revision = 'a06ef37f9e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapped_locations',
    sa.Column('unmatched_id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_locations.id'], ),
    sa.ForeignKeyConstraint(['unmatched_id'], ['unmatched_locations.id'], ),
    sa.PrimaryKeyConstraint('unmatched_id')
    )
    with op.batch_alter_table(u'indicator_groups', schema=None) as batch_op:
        batch_op.alter_column('text_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'indicator_groups', schema=None) as batch_op:
        batch_op.alter_column('text_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('mapped_locations')
    # ### end Alembic commands ###
