"""Create initial models for indicator db functionality.

Revision ID: f66b2477cc4d
Revises: 58ea420663e7
Create Date: 2020-04-23 14:01:25.545748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f66b2477cc4d'
down_revision = '58ea420663e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'dimension',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'field',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('short_name', sa.String(), nullable=False),
        sa.Column(
            'calculation', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'pipeline_datasource',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'category_to_category_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.String(), nullable=False),
        sa.Column('parent_category_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'], ['category.id'], name='valid_category', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['parent_category_id'],
            ['category.id'],
            name='valid_parent_category',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('category_id', 'parent_category_id'),
    )
    op.create_table(
        'field_category_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('field_id', sa.String(), nullable=False),
        sa.Column('category_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'], ['category.id'], name='valid_category', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['field_id'], ['field.id'], name='valid_field', ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('field_id', 'category_id'),
    )
    op.create_table(
        'field_dimension_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('field_id', sa.String(), nullable=False),
        sa.Column('dimension_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['dimension_id'],
            ['dimension.id'],
            name='valid_dimension',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['field_id'], ['field.id'], name='valid_field', ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('field_id', 'dimension_id'),
    )
    op.create_table(
        'field_pipeline_datasource_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('field_id', sa.String(), nullable=False),
        sa.Column('pipeline_datasource_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['field_id'], ['field.id'], name='valid_field', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['pipeline_datasource_id'],
            ['pipeline_datasource.id'],
            name='valid_pipeline_datasource',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('field_id', 'pipeline_datasource_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_pipeline_datasource_mapping')
    op.drop_table('field_dimension_mapping')
    op.drop_table('field_category_mapping')
    op.drop_table('category_to_category_mapping')
    op.drop_table('pipeline_datasource')
    op.drop_table('field')
    op.drop_table('dimension')
    op.drop_table('category')
    # ### end Alembic commands ###
