"""alerts: Add compared_val column to AlertDefinition

Revision ID: fa4b961b5ecd
Revises: 1183eb8e2a0a
Create Date: 2021-08-05 11:41:08.225832

"""
# pylint: disable-all

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa4b961b5ecd'
down_revision = '1183eb8e2a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compared_val', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.drop_column('compared_val')

    # ### end Alembic commands ###
