# pylint: disable=invalid-name
"""Only allow a single dashboard report generator to be created per dashboard

Revision ID: fcd59de9d36d
Revises: 1e6aa4f75d79
Create Date: 2023-01-08 13:31:25.001823

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fcd59de9d36d'
down_revision = '1e6aa4f75d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_generator', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'dashboard_report_generator_dashboard_id_key', ['dashboard_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_generator', schema=None) as batch_op:
        batch_op.drop_constraint(
            'dashboard_report_generator_dashboard_id_key', type_='unique'
        )

    # ### end Alembic commands ###
