#!/bin/bash -eu
set -o pipefail

"${PIPELINE_SRC_ROOT}/db/druid/indexing/scripts/run_indexing.py" \
  --data_files='/home/share/data/SAMPLE/*/current/processed_rows.*' \
  --output_task_id_file="${PIPELINE_TMP_DIR}/task_id" \
  --min_data_date='1970-01-01'
