#!/usr/bin/env python

# maps from the deployment web role to the phab passphrase for the technical-support account
DEPLOYMENT_CREDENTIALS_MAP = {
    'afsa-prod': 182,
    'alliance-india-prod': 133,
    'bd-prod-2': 142,
    'bd-prod': 142,
    'beyond-zero-prod': 155,
    'bj-web-prod': 173,
    'bj-web-stating': 261,
    'br-covid-web-prod': 204,
    'br-prod': 278,
    'et-internal-web-prod': 126,
    'et-jcc-web-prod': 207,
    'et-web-staging': 254,
    'gates-malaria-web-prod': 220,
    'ke-web-demo': 208,
    'ke-web-prod': 135,
    'kvapsa-web-prod': 230,
    'mz-covid-web-prod': 189,
    'mz-prod': 152,
    'nacosa-legacy-prod': 136,
    'pk-web-aws-prod': 167,
    'pk-web-ntc-prod': 167,
    'rw-internal-web-prod': 132,
    'tg-prod': 127,
    'za-prod': 129,
    'zen': 252,
    'zm-web-prod': 128,
}
