#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        // Checkout github project
        stage('Checkout') {
          steps {
            git url: "https://github.com/Zenysis/Harmony.git", branch: 'need-buildkit'
          }
        }
        // Build all docker web containers
        stage('Web Build') {
            steps {
                sh 'make web-client-build'
                sh 'make web-server-build'
                sh 'make web-build'
            }
        }
        // Push all docker web containers to https://hub.docker.com/u/zengineering
        stage('Web Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-io-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                    sh 'make web-client-push'
                    sh 'make web-server-push'
                    sh 'make web-push'
                    sh 'docker logout'
                }
            }
        }
        // Build all docker pipeline containers
        stage('Pipeline Build') {
            steps {
                sh 'make etl-pipeline-build'
            }
        }
        // Push all docker pipeline containers to https://hub.docker.com/u/zengineering
        stage('Pipeline Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-io-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                    sh 'make etl-pipeline-push'
                    sh 'docker logout'
                }
            }
        }
    }
}
