// @flow

// A comprehensive list of all the variables with corresponding values returned
// by the risk scores model
type RiskScoreVariable = [
  'race_black',
  'race_coloured',
  'race_indian',
  'race_white',
  'Female',
  'Transgender',
  'age_16-25',
  'age_26-35',
  'age_36-50',
  'age_51+',
  'PWID',
  'swt_Brothel',
  'swt_Bush',
  'swt_Home',
  'swt_Hotel',
  'swt_House',
  'swt_Internet',
  'swt_Street',
  'swt_Tavern',
  'swt_Truck',
  'risk_High',
  'risk_Low',
  'risk_Medium',
  'num_appts',
  'wks_since_first',
  'wks_since_last',
  'trauma_client',
  'trauma_communitymember',
  'trauma_healthcareworker',
  'trauma_partner',
  'trauma_police',
  'trauma_tavernowner',
  'trauma_sum',
  'b1_sws_tested_and_know_result',
  'b4b_known_positive_linked_to_care',
  'b4c_known_positive_initiated_on_art',
  'b5a_known_positive_referred_for_art_all',
  'b5c_known_positive_on_art',
  'b7a_recieved_viral_load_test',
  'b7b_recieved_viral_load_test_and_undetected_viral_load',
  'b7c_referred_for_viral_load_test',
  'b7d_successfully_referred_for_viral_load_test',
  'b10a_referred_for_adherence_support',
  'b10b_successfully_referred_for_adherence_support',
  'b10c_provided_adherence_support',
  'b11_cd4_count',
  'c1_sti_screening',
  'c2a_referred_for_sti_treatment',
  'c2b_linked_to_care_for_sti_treatment',
  'c2c_initiated_on_sti_treatment',
  'c3_currently_on_sti_treatment',
  'd1_tb_screening',
  'd2a_referred_for_tb_treatment',
  'd2b_linked_to_care_for_tb_treatment',
  'd2c_initiated_on_tb_treatment',
  'd3_currently_on_tb_treatment',
  'f1_male_condoms_distributed',
  'f2_female_condoms_distributed',
  'f3_recieved_lube',
  'h1a_familyplanning_pregnancytest',
  'h1b_referral_pregnancytest',
  'h1c_pregnancytest_pmtct_successfully_referred',
  'h1d_antenatal_services_successfully_referred',
  'h1e_successful_referral_top',
  'h2a_provided_contraception',
  'h2b_referral_contraception',
  'h2c_provided_emergencycontraception',
  'h2d_referral_emergencycontraception',
  'h3a_provided_papsmear',
  'h3b_referrals_papsmear',
  'h3c_provided_breastexamination',
  'h3d_referrals_breastexamination',
  'h4a_screened_hypertention',
  'h4b_referral_hypertention',
  'h4c_diabetes_screening',
  'h4d_referral_diabetessuspect',
  'marked_default',
  'marked_no_default',
  'FamilyPlanning_1',
  'FamilyPlanning_0',
  'SexualHealth_1',
  'SexualHealth_0',
  'NonCommunicable_1',
  'NonCommunicable_0',
  'ReasonNotOnArt',
];

export type RiskScoreDataPoint = {
  avg: number,
  term: number,
  type: 'Positive' | 'Negative' | 'None',
  value: number,
  variable: RiskScoreVariable,
};
