// @flow

export type ResultViewTypeMap = {
  BAR_GRAPH: 'BAR_GRAPH',
  BOX_PLOT: 'BOX_PLOT',
  BUBBLE_CHART: 'BUBBLE_CHART',
  BUMP_CHART: 'BUMP_CHART',
  EPICURVE: 'EPICURVE',
  EXPANDOTREE: 'EXPANDOTREE',
  HEATTILES: 'HEATTILES',
  MAP: 'MAP',
  NUMBER_TREND: 'NUMBER_TREND',
  PIE: 'PIE',
  SUNBURST: 'SUNBURST',
  TABLE: 'TABLE',
  TIME: 'TIME',
};

export type ResultViewType = $Keys<ResultViewTypeMap>;

export const RESULT_VIEW_TYPES: ResultViewTypeMap = {
  BAR_GRAPH: 'BAR_GRAPH',
  BOX_PLOT: 'BOX_PLOT',
  BUBBLE_CHART: 'BUBBLE_CHART',
  BUMP_CHART: 'BUMP_CHART',
  EPICURVE: 'EPICURVE',
  EXPANDOTREE: 'EXPANDOTREE',
  HEATTILES: 'HEATTILES',
  MAP: 'MAP',
  NUMBER_TREND: 'NUMBER_TREND',
  PIE: 'PIE',
  SUNBURST: 'SUNBURST',
  TABLE: 'TABLE',
  TIME: 'TIME',
};
