#!/bin/bash -eu
set -o pipefail

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

rm -rf "${PIPELINE_FEED_DIR}"/*

curl 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/Febre+Amarela/fa_casoshumanos_1994-2021.csv' \
    | iconv -f ISO-8859-1 -t UTF-8//TRANSLIT \
    > yellow_fever_cases.csv

popd &> /dev/null
