#!/bin/bash -eu
set -o pipefail

source "${PIPELINE_UTILS_DIR}/bash/common.sh"

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

# latest_dir=$(GetLatestDirectory 's3/zenysis-SITECODE/foo' 'somefile.xlsx')
# FetchFiles "${latest_dir}/*.csv.lz4" .

popd &> /dev/null
