// @flow

export const RISK_SCORE_INDICATOR_ID = 'pct_prob';
export const RISK_SCORE_GROUPING_DIMENSION = 'sw_unique_id';
// This text will never not be in english, so we don't need to put it in the
// translation file
export const RISK_SCORE_TEXT = {
  tooltip: 'Click to see details',
  RiskScoreModal: {
    title: 'What is this score?',
    RiskScoreOverviewSection: {
      summary: {
        swId: 'SW ID:',
        probabilityScore: 'Probability Score:',
        overview: {
          start: 'Overview: ',
          middle:
            'this probability score is generated by a logistic regression model trained on the data for HIV-positive sex workers who have been seen at a clinic since January 2019. The model has been optimized to accurately identify those who are likely not to be retained. Full details on the overall methodology, metrics on how the model performs, and details on data sources & variables can be found ',
          end: 'here.',
        },
      },
      disclaimer: {
        start:
          'In an effort to make the model as transparent as possible, you will find the full set of variables that the model takes as input, organized in tabs and sorted by their relative impact on this particular probability score.',
        end:
          'While we hope this allows for a better sense of what\'s going on "under the hood", it is very important to note that no conclusions can be drawn about causal relationships between each of these specific variables and the overall predicted probability of retention.',
        examples: {
          intro:
            "The model's goal is to produce an overall prediction leveraging all available data - not to identify or explore causal relationships between individual variables and outcomes. 3 examples to help illustrate this:",
          missingVariables: {
            start: 'Missing variables: ',
            end:
              'many variables that impact retention were not available or included in the data at all - for example, income. If one of the variables the model does consider happens to be correlated with income, it would have an impact on the score - but only because it correlates with income and not because the variable itself actually has a direct causal impact on probability of retention.',
          },
          missingValues: {
            start: 'Missing values: ',
            end:
              'there are many missing values in the data. For example, many individuals have no race specified. If the variable race_black increases probability of retention, it could actually be a reflection of data collection issues, for example whether a peer educator recorded race at all, rather than an individual being a specific race.',
          },
          trainingData: {
            start: 'Training data is not broadly representative: ',
            end:
              'the model has been trained on the data for HIV-positive sex workers who have been seen at a clinic since January 2019. This means even if there were any valid causal relationships identified, they would not necessarily apply to the broader population.',
          },
        },
      },
    },
    questionsConcerns:
      "Please don't hesitate to reach out to us with any questions or concerns.",
    definitions: {
      start:
        "Definitions for each variable can be found in the 'Model input data' section in the ",
      end: 'overview doc.',
    },
    RiskScoreTables: {
      internalTabs: {
        positiveHeader: 'Positive retention variables',
        negativeHeader: 'Negative retention variables',
        allHeader: 'All variables',
      },
      internalTable: {
        impactOnScore: 'Level of Impact on Score',
        type: 'Type of Impact',
        factor: 'Factor',
        value: 'Value',
        average: 'Average Value (All SWs)',
      },
    },
  },
};
