name: harmony-postgres
networks:
  harmony_postgres_network:
    name: harmony_postgres_network
    driver: bridge
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_HOST_MOUNT-./postgresql/data}:/var/lib/postgresql/data
    networks:
      - harmony_postgres_network
