name: Web Image

on:
    # Trigger on all pull requests.
    pull_request:
    # Trigger on all pushes to main.
    push:
      branches:
        - main

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - id: repository_name
              run: |
                lowercase_repo_name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
                echo "lowercase_repo_name=${lowercase_repo_name}" >> $GITHUB_OUTPUT
        outputs:
            lowercase_repo_name: ${{ steps.repository_name.outputs.lowercase_repo_name }}

    build-web-client:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-web-client
              run: |
                docker build --platform linux/amd64 -t ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-client:${{ github.head_ref || github.ref_name }} -f docker/web/Dockerfile_web-client --cache-from ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-client:main,ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-client:${{ github.head_ref || github.ref_name }} --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-client:${{ github.head_ref || github.ref_name }}
    build-web-server:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-web-server
              run: |
                docker build --platform linux/amd64 -t ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-server:${{ github.head_ref || github.ref_name }} -f docker/web/Dockerfile_web-server --cache-from ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-server:main,ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-server:${{ github.head_ref || github.ref_name }} --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web-server:${{ github.head_ref || github.ref_name }}
    build-web-image:
        needs: [prepare, build-web-client, build-web-server]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-web-image
              run: |
                docker build --platform linux/amd64 -t ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web:${{ github.head_ref || github.ref_name }} -f docker/web/Dockerfile_web --build-arg NAMESPACE=ghcr.io/zenysis --build-arg IMAGE_PREFIX=${{ needs.prepare.outputs.lowercase_repo_name }} --build-arg TAG=${{ github.head_ref || github.ref_name }} --cache-from ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web:main,ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web:${{ github.head_ref || github.ref_name }} --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push ghcr.io/zenysis/${{ needs.prepare.outputs.lowercase_repo_name }}-web:${{ github.head_ref || github.ref_name }}