# pylint: disable=invalid-name
# pylint: disable=line-too-long
"""Adds a reference to PipelineDatasource in SelfServeSource.

Revision ID: 1d09a4f69ae4
Revises: de1372d2c1b3
Create Date: 2021-11-19 11:14:47.204754

"""
from alembic import op
import sqlalchemy as sa
from web.server.migrations.seed_scripts.seed_1d09a4f69ae4_add_self_serve_source_pipeline_source_fk import (
    upvert_data,
    downvert_data,
)

# revision identifiers, used by Alembic.
revision = '1d09a4f69ae4'
down_revision = 'de1372d2c1b3'
branch_labels = None
depends_on = None


def upgrade():
    upvert_data(op)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, 'pipeline_datasource', ['source_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.drop_column('source_name')

    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.drop_constraint('self_serve_source_source_id_fkey', type_='foreignkey')
        batch_op.add_column(
            sa.Column('source_name', sa.String(length=100), autoincrement=False)
        )

    downvert_data(op)
    # ### end Alembic commands ###
