"""Create a temporary `legacy_specification` column in the dashboard table so that users
can still view their non-upgraded dashboard during the launch of the modern dashboard
experience.

Revision ID: 1ee42f0ba37d
Revises: c35c7fbe172f
Create Date: 2021-09-16 12:47:17.448480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ee42f0ba37d'
down_revision = 'c35c7fbe172f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dashboard',
        sa.Column(
            'legacy_specification',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.execute('UPDATE dashboard SET legacy_specification = specification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('legacy_specification')

    # ### end Alembic commands ###
