"""Add show_case_type_in_dossier to case_type table

Revision ID: 1fdcf826e468
Revises: 1683303b140a
Create Date: 2020-07-24 14:30:13.637953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdcf826e468'
down_revision = '1683303b140a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_type', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'show_case_type_in_dossier',
                sa.Boolean(),
                nullable=True,
                server_default='true',
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_type', schema=None) as batch_op:
        batch_op.drop_column('show_case_type_in_dossier')

    # ### end Alembic commands ###
