"""Add quarterly and semi-annual scheduled dashboard reporting periods

Revision ID: 4c19fa30d958
Revises: 84a8f91cfbb3
Create Date: 2022-05-31 01:29:19.797446

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
# pylint: disable=invalid-name
revision = '4c19fa30d958'
down_revision = '84a8f91cfbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crontab_schedule', schema=None) as batch_op:
        batch_op.alter_column(
            'month_of_year',
            existing_type=sa.VARCHAR(length=2),
            type_=sa.String(length=4),
            existing_nullable=True,
        )

    op.execute("ALTER TYPE schedule_cadence_enum RENAME TO schedule_cadence_enum_old")
    op.execute(
        "CREATE TYPE schedule_cadence_enum AS ENUM('DAILY', 'WEEKLY','MONTHLY','ANNUALLY','QUARTERLY','SEMIANNUALLY')"
    )
    op.execute(
        (
            "ALTER TABLE dashboard_report_schedule ALTER COLUMN cadence TYPE schedule_cadence_enum USING "
            "cadence::text::schedule_cadence_enum"
        )
    )
    op.execute("DROP TYPE schedule_cadence_enum_old")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crontab_schedule', schema=None) as batch_op:
        batch_op.alter_column(
            'month_of_year',
            existing_type=sa.String(length=4),
            type_=sa.VARCHAR(length=4),
            existing_nullable=True,
        )

    # NOTE (solo): Don't downgrade the enum values as it will break the dashboard_report_schedule
    # if we have used the new values.

    # ### end Alembic commands ###
