# pylint: disable=invalid-name
"""Creates a table for dashboard report generators and corresponding storage space
to store its recipient groups

Revision ID: 5259b9c6d7a6
Revises: eb1742dac26e
Create Date: 2022-11-08 16:01:42.085933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5259b9c6d7a6'
down_revision = 'eb1742dac26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dashboard_report_generator',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('dashboard_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('query_link_id', sa.String(), nullable=False),
        sa.Column('recipients', postgresql.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ['dashboard_id'],
            ['dashboard.id'],
            name='valid_dashboard_report_schedule',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'], ['user.id'], name='valid_owner', ondelete='RESTRICT'
        ),
        sa.ForeignKeyConstraint(
            ['query_link_id'],
            ['user_query_session.query_uuid'],
            name='valid_query',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('dashboard_report_groups', schema=None) as batch_op:
        batch_op.alter_column(
            'dashboard_report_id',
            new_column_name='dashboard_report_schedule_id',
            nullable=True,
        )
        batch_op.add_column(
            sa.Column('dashboard_report_generator_id', sa.Integer(), nullable=True)
        )
        batch_op.drop_constraint('valid_dashboard_report_group', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_dashboard_report_generator',
            'dashboard_report_generator',
            ['dashboard_report_generator_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'valid_dashboard_report_schedule',
            'dashboard_report_schedule',
            ['dashboard_report_schedule_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_check_constraint(
            'report_specified',
            condition='dashboard_report_schedule_id IS NOT NULL OR '
            'dashboard_report_generator_id IS NOT NULL',
        )
        batch_op.create_unique_constraint(
            'unique_group_per_report_generator',
            ['dashboard_report_generator_id', 'group_id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_report_groups', schema=None) as batch_op:
        batch_op.drop_constraint('report_specified')
        batch_op.drop_constraint('unique_group_per_report_generator', type_='unique')
        batch_op.alter_column(
            'dashboard_report_schedule_id',
            new_column_name='dashboard_report_id',
            nullable=False,
        )
        batch_op.drop_constraint('valid_dashboard_report_schedule', type_='foreignkey')
        batch_op.drop_constraint('valid_dashboard_report_generator', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_dashboard_report_group',
            'dashboard_report_schedule',
            ['dashboard_report_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.drop_column('dashboard_report_generator_id')

    op.drop_table('dashboard_report_generator')
    # ### end Alembic commands ###
