"""Removes default_roles and introduces sitewide_acl table

Revision ID: 546034ace769
Revises: 856eb1abdbce
Create Date: 2020-03-31 16:50:21.243948

"""
from alembic import op
import sqlalchemy as sa

from web.server.migrations.seed_scripts.seed_546034ace769_rm_default_roles_add_sitewide_acl import (
    upvert_data,
    downvert_data,
)

# revision identifiers, used by Alembic.
revision = '546034ace769'
down_revision = '856eb1abdbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sitewide_resource_acl',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=False),
        sa.Column('registered_resource_role_id', sa.Integer(), nullable=True),
        sa.Column('unregistered_resource_role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['registered_resource_role_id'],
            ['resource_role.id'],
            name='valid_registered_resource_role',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['resource_id'], ['resource.id'], name='valid_resource', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['unregistered_resource_role_id'],
            ['resource_role.id'],
            name='valid_unregistered_resource_role',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('resource_id'),
    )

    upvert_data(op)

    op.drop_table('default_roles')
    with op.batch_alter_table('query_policy', schema=None) as batch_op:
        batch_op.alter_column(
            'query_policy_type_id', existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_policy', schema=None) as batch_op:
        batch_op.alter_column(
            'query_policy_type_id', existing_type=sa.INTEGER(), nullable=True
        )

    op.create_table(
        'default_roles',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            'apply_to_unregistered',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['resource_id'], ['resource.id'], name='valid_resource', ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['role_id'], ['role.id'], name='valid_role', ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name='public_roles_pkey'),
    )

    downvert_data(op)

    op.drop_table('sitewide_resource_acl')
    # ### end Alembic commands ###
