"""allow null file summary

Revision ID: 59f23455295a
Revises: 1bb8b462a580
Create Date: 2021-09-15 15:57:33.923637

"""

# pylint: disable-all
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59f23455295a'
down_revision = '1ee42f0ba37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.alter_column(
            'file_summary_id', existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.alter_column(
            'file_summary_id', existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
