"""Updates ondelete for resource roles

Revision ID: 6722855f6ce5
Revises: 93bb8d693499
Create Date: 2020-08-28 17:00:08.314648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6722855f6ce5'
down_revision = '93bb8d693499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('valid_alert_resource_role', type_='foreignkey')
        batch_op.drop_constraint('valid_dashboard_resource_role', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_alert_resource_role',
            'resource_role',
            ['alert_resource_role_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.create_foreign_key(
            'valid_dashboard_resource_role',
            'resource_role',
            ['dashboard_resource_role_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('valid_dashboard_resource_role', type_='foreignkey')
        batch_op.drop_constraint('valid_alert_resource_role', type_='foreignkey')
        batch_op.create_foreign_key(
            'valid_dashboard_resource_role',
            'resource_role',
            ['dashboard_resource_role_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'valid_alert_resource_role',
            'resource_role',
            ['alert_resource_role_id'],
            ['id'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###
