"""Add feed update objects

Revision ID: 678bbb66356c
Revises: 1a712d1436eb
Create Date: 2020-01-16 13:41:06.636352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from web.server.migrations.seed_scripts.seed_678bbb66356c import upvert_data

# revision identifiers, used by Alembic.
revision = '678bbb66356c'
down_revision = '1a712d1436eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'feed_update_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'feed_update',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('feed_update_type_id', sa.Integer(), nullable=True),
        sa.Column(
            'notification_payload',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column('datasource', sa.String(), nullable=True),
        sa.Column('generation_timestamp', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['feed_update_type_id'], ['feed_update_type.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    upvert_data(op)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_update')
    op.drop_table('feed_update_type')
    # ### end Alembic commands ###
