# pylint: disable=invalid-name
"""This migration generates the materialized views used to make entity matching quicker

Revision ID: 6aec17d57ff8
Revises: 3c3ef4a761ed
Create Date: 2023-03-03 15:54:23.356393

"""
from alembic import op

from web.server.migrations.seed_scripts.seed_6aec17d57ff8_add_entity_matching_materialized_views import (
    upvert_data,
    downvert_data,
)


# revision identifiers, used by Alembic.
revision = '6aec17d57ff8'
down_revision = '3c3ef4a761ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    upvert_data(op)

    # ### end Alembic commands ###


def downgrade():
    downvert_data(op)
