"""Add DataprepFlow and DataprepJob Tables and a foreignkey on SelfServeSource to DataprepFlow

Revision ID: 77142d54b64d
Revises: fa4b961b5ecd
Create Date: 2021-08-25 11:46:13.066993

"""
# pylint: disable-all
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77142d54b64d'
down_revision = 'fa4b961b5ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dataprep_flow',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'expected_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('recipe_id'),
    )
    op.create_table(
        'dataprep_job',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_on_dataprep', sa.DateTime(), nullable=False),
        sa.Column('last_modified_on_dataprep', sa.DateTime(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=100), nullable=True),
        sa.Column('dataprep_flow_id', sa.Integer(), nullable=False),
        sa.Column(
            'created', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'last_modified',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['dataprep_flow_id'], ['dataprep_flow.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('job_id'),
    )

    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataprep_flow_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, 'dataprep_flow', ['dataprep_flow_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_serve_source', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dataprep_flow_id')

    op.drop_table('dataprep_job')
    op.drop_table('dataprep_flow')
    # ### end Alembic commands ###
