"""Adds case_type_metadata_from_druid_field table

Revision ID: 915286bb532c
Revises: 86cb7933619c
Create Date: 2020-05-25 10:48:27.744096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915286bb532c'
down_revision = '86cb7933619c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'case_type_metadata_from_druid_field',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('case_type_id', sa.Integer(), nullable=False),
        sa.Column('field_id', sa.Text(), nullable=False),
        sa.Column('display_name', sa.Text(), nullable=False),
        sa.Column(
            'type',
            sa.Enum('NUMBER', 'BOOLEAN', name='druidfieldmetadatatypeenum'),
            nullable=False,
        ),
        sa.Column('show_in_overview_table', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['case_type_id'],
            ['case_type.id'],
            name='valid_case_type',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_type_metadata_from_druid_field')
    op.execute('drop type druidfieldmetadatatypeenum;')
    # ### end Alembic commands ###
