# pylint: disable=C0103
# pylint: disable=E1101
# pylint: disable=C0301
"""Remove HistoryRecord model

Revision ID: 925fed9a10e4
Revises: 347d0217289b
Create Date: 2022-07-29 08:28:44.586071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '925fed9a10e4'
down_revision = '347d0217289b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.drop_index('ix_history_records_object_id')
        batch_op.drop_index('ix_history_records_object_type')

    op.drop_table('history_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'history_records',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'object_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'changes',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'created',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name='valid_user', ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id', name='history_records_pkey'),
    )
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.create_index(
            'ix_history_records_object_type', ['object_type'], unique=False
        )
        batch_op.create_index(
            'ix_history_records_object_id', ['object_id'], unique=False
        )

    # ### end Alembic commands ###
