"""Creates field in role for dashboard resourceRole

Revision ID: a43bff717c71
Revises: 546034ace769
Create Date: 2020-04-09 16:44:35.727488

"""
from alembic import op
import sqlalchemy as sa

from web.server.migrations.seed_scripts.seed_a43bff717c71_add_dash_resourcerole_to_role import (
    upvert_data,
    downvert_data,
)


# revision identifiers, used by Alembic.
revision = 'a43bff717c71'
down_revision = '546034ace769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('alert_resource_role_id', sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('dashboard_resource_role_id', sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            'valid_alert_resource_role',
            'resource_role',
            ['alert_resource_role_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            'valid_dashboard_resource_role',
            'resource_role',
            ['dashboard_resource_role_id'],
            ['id'],
            ondelete='CASCADE',
        )
    # ### end Alembic commands ###
    upvert_data(op)


def downgrade():
    downvert_data(op)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('valid_dashboard_resource_role', type_='foreignkey')
        batch_op.drop_constraint('valid_alert_resource_role', type_='foreignkey')
        batch_op.drop_column('dashboard_resource_role_id')
        batch_op.drop_column('alert_resource_role_id')

    # ### end Alembic commands ###
