# pylint: disable=invalid-name
"""Adds a new table to track current report generator run

Revision ID: b281ae64d45d
Revises: 2235d00f9ebb
Create Date: 2022-12-08 14:30:35.807991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b281ae64d45d'
down_revision = '2235d00f9ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dashboard_report_run',
        sa.Column('task_id', sa.String(), nullable=False),
        sa.Column(
            'started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column('dashboard_report_generator_id', sa.Integer(), nullable=False),
        sa.Column('successful', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['dashboard_report_generator_id'],
            ['dashboard_report_generator.id'],
            name='valid_dashboard_report_generator',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('task_id'),
        sa.UniqueConstraint('dashboard_report_generator_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_report_run')
    # ### end Alembic commands ###
