"""Standardize enum type names that were previously unspecified.

Revision ID: c35c7fbe172f
Revises: 1bb8b462a580
Create Date: 2021-09-16 12:29:05.625043

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c35c7fbe172f'
down_revision = '1bb8b462a580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TYPE druidfieldmetadatatypeenum RENAME TO druid_field_metadata_type_enum'
    )
    op.execute('ALTER TYPE querypolicytypeenum RENAME TO query_policy_type_enum')
    op.execute('ALTER TYPE userstatusenum RENAME TO user_status_enum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TYPE druid_field_metadata_type_enum RENAME TO druidfieldmetadatatypeenum'
    )
    op.execute('ALTER TYPE query_policy_type_enum RENAME TO querypolicytypeenum')
    op.execute('ALTER TYPE user_status_enum RENAME TO userstatusenum')

    # ### end Alembic commands ###
