"""Migrate query policy resources to roles.

Revision ID: ca5ccf4e8a59
Revises: 93bb8d693499
Create Date: 2020-06-08 16:10:29.539861

"""
from alembic import op
import sqlalchemy as sa

from web.server.migrations.seed_scripts.seed_ca5ccf4e8a59_migrate_query_policy_resources_to_roles import (
    upvert_data,
    downvert_data,
)


# revision identifiers, used by Alembic.
revision = 'ca5ccf4e8a59'
down_revision = '9a485a630d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_policy', schema=None) as batch_op:
        batch_op.drop_constraint('query_policy_resource_id_key', type_='unique')
        batch_op.drop_constraint('valid_query_definition_resource', type_='foreignkey')
        batch_op.drop_column('resource_id')
    upvert_data(op)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_policy', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            'valid_query_definition_resource',
            'resource',
            ['resource_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_unique_constraint(
            'query_policy_resource_id_key', ['resource_id']
        )
    downvert_data(op)
    # ### end Alembic commands ###
