"""empty message

Revision ID: de78dcd90eb3
Revises: 34ef9489bfc1
Create Date: 2020-05-26 16:06:07.294699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de78dcd90eb3'
down_revision = '34ef9489bfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_metadata_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dossier_section', sa.Text(), nullable=True))

    with op.batch_alter_table(
        'case_type_default_druid_dimension', schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column('dossier_section', sa.Text(), nullable=True))

    with op.batch_alter_table(
        'case_type_metadata_from_druid_field', schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column('dossier_section', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'case_type_metadata_from_druid_field', schema=None
    ) as batch_op:
        batch_op.drop_column('dossier_section')

    with op.batch_alter_table(
        'case_type_default_druid_dimension', schema=None
    ) as batch_op:
        batch_op.drop_column('dossier_section')

    with op.batch_alter_table('case_metadata_type', schema=None) as batch_op:
        batch_op.drop_column('dossier_section')

    # ### end Alembic commands ###
