"""Delete `message` column from alert_notifications table

Revision ID: fc7d305d0341
Revises: 0899aad0cf2f
Create Date: 2021-09-13 12:17:36.316154

"""
# pylint: disable-all

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc7d305d0341'
down_revision = '0899aad0cf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
